# remember to run "docker build -t cicdont/frontend ." and
# "docker build -t cicdont/backend ." in root directories minitwit-front 
# and minitwit-backend, respectively, before running this file with command
# "docker-compose up"
services:
  frontend:
    image: registry.digitalocean.com/cicdont-images/frontend
    container_name: frontend
    # service_name: frontend
    ports:
      - "3000:3000"
    environment:
      API_URL: http://138.68.93.147:8080
    depends_on:
      - backend
  backend:
    image: registry.digitalocean.com/cicdont-images/backend
    container_name: api
    # service_name: api
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - ./backend/.env
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 60 # seconds between checks
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - "4000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  prometheus_data: {}
  grafana: