# remember to run "docker build -t cicdont/frontend ." and
# "docker build -t cicdont/backend ." in root directories minitwit-front 
# and minitwit-backend, respectively, before running this file with command
# "docker-compose up"
services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:8080
  backend:
    build:
      context: ./backend
    container_name: api
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - ./backend/.env
    command:
      - test
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - "4000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  prometheus_data: {}
  grafana: