name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pdf-to-tex:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up TeX Live environment
        uses: docker://texlive/texlive:latest

      - name: Build PDF
        run: |
          cd report
          pdflatex -interaction=nonstopmode main.tex
          biber main
          pdflatex -interaction=nonstopmode main.tex
          pdflatex -interaction=nonstopmode main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: report-pdf
          path: report/main.pdf
