name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tex-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Convert to pdf
        id: convert-to-pdf
        uses: closoco/pdflatex-action@v1.1.0
        with:
          texFile: ./report/main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: report-pdf
          path: report/main.pdf
