name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pdf-to-tex:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: install texlive
        run: sudo apt-get install texlive -y
    
      - name: install texinfo
        run: sudo apt-get install texinfo -y

      - name: install texlive-fonts-recommended 
        run: sudo apt-get install texlive-fonts-recommended -y

      - name: install texlive-fonts-extra
        run: sudo apt-get install texlive-fonts-extra -y
    
      - name: install texlive-latex-extra
        run: sudo apt-get install texlive-latex-extra -y

      - name: Build PDF
        run: pdflatex /report/main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: report-pdf
          path: report/main.pdf
