name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          package-file: 
            report/packages.txt

      - name: Check `tlmgr` version
        run: tlmgr --version

      - name: Build PDF
        run: |
          cd report
          pdftex /report/main.tex 

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: report-pdf
          path: report/main.pdf
