name: Continuous Integration

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build TEST API Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./itu-minitwit/backend
          dockerfile: ./itu-minitwit/backend/Dockerfile-test
          push: false
          tags: api-test:latest
      
  api_tests:
    runs-on: ubuntu-latest
    services:
      api:
        image: api-test:latest
        ports:
          - 8080:8080
          - 8081:8081
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
    steps:
      - name: Load Docker image
        uses: docker/load-action@v2
        with:
          image: api-test:latest
          load_path: api-test-latest.tar
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Run Go APIs & test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          /usr/bin/docker run -d -p 8080:8080 -p 8081:8081 api-test:latest    
          (cd itu-minitwit/backend/test && go test -v ./...)
