name: Continuous Integration

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  api_tests:
    runs-on: ubuntu-latest 
    services:
      api:
        image: ubuntu:latest
        ports:
          - 8080/tcp
          - 8081/tcp
        options: --entrypoint "cd itu-minitwit/backend/Main && go run main.go test"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Run Go APIs & test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |    
          (cd itu-minitwit/backend/test && go test -v ./...)
